config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  devise_for :customer_users
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/customer_user.rb
class CustomerUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :author,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
<div class="card" style="width: 250px;" >
  <div class="card-body">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> 
     <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p></li>
    <li class="list-group-item">
  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p></li>
    <li class="list-group-item">  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p></li>
  </ul>
</div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  


    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  

    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  <br>

  <%= form.label :image%>
  <%=form.file_field :image%>
  

    <%= form.submit %>
  
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
<%= render "form", book: @book %>
<br>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Books</h1>
<div id="books">
  <% @books.each do |book| %>
  
   <%= render book %><%= link_to "New book", new_book_path %>
  <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= render "form", book: @book %>
<br>
<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @book %>

  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Books Library 📚</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", books_path , class:"nav-link" %>
   </li>
      <li class="nav-item">
      <%= link_to "Sign Up",  new_customer_user_registration_path , class: "nav-link" %>
      </li>
       <li class="nav-item">
      <%= link_to "Sign In",  new_customer_user_session_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Sign Up</a>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>

  </body>
</html>